#version: "3"
#services:
#  sucatDB:
#    container_name: sucatDB
#    image: mysql:8.0.32
#    restart: always
#    volumes:
##      - mysql_volume:/app/mysql
#      - ./db:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=
#      - MYSQL_DATABASE=mydb
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=1234
#    ports:
#      - "3306:3306"
#    networks:
#      - sucat
#    healthcheck:
#      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
#      timeout: 20s
#      retries: 10
#  sucatServer:
#    container_name: sucatServer
#    ports:
#      - "8080:8080"
#    image: pp8817/sucat_backend_server:1.0
#    volumes:
#      - 8am_images:/app/8am/images
#    networks:
#      - sucat
#    depends_on:
#      sucatDB:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://sucatDB:3306/dms
#networks:
#  8am-net:
#    driver: bridge
#volumes:
#  mysql_volume:
#    driver: local
#  8am_images:
#    driver: local